// generated by "sampctl package init"
#include <a_samp>
#include <a_mysql>
#include <Pawn.CMD>
#include <sscanf2>

new MySQL:g_sql;

#define HOSTNAME        "Project: Vhocan"
#define GAMEMODETEXT	"SAMPCTL v1"

main() 
{
	// SAMPCTL's purposes are only for windows server/testing/creating library/etc... //
	/*
		sampctl p build = compile. Make sure to save your pwn file before compiling
		sampctl p run = for running the server.
		exit = to stop the server from running.
	*/
}

public OnGameModeInit(){
	g_sql = mysql_connect("127.0.0.1", "root", "", "mydatabase");
	if(mysql_errno() != 0) 
		print("Could not connect to database!");
	else
		print("Database Connected");
	
	SendRconCommand("hostname "HOSTNAME"");
	SetGameModeText(GAMEMODETEXT);
	print("[SAMPCTL]: "HOSTNAME"");
	return 1;
}

public OnPlayerConnect(playerid){

	return 1;
}